<a href="https://colab.research.google.com/github/garestrear/metodos_numericos/blob/main/M%C3%A9todos_de_Sistemas_de_Ecuaciones_en_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#<h1><center> UNIVERSIDAD NACIONAL DE COLOMBIA </center></h1>
# <h1><center>SEDE MEDELLÍN</center></h1>
# <h1><center>MÉTODOS NUMÉRICOS</center></h1>

## CAPÍTULO 2. SOLUCIÓN NUMÉRICA DE SISTEMAS DE ECUACIONES LINEALES Y NO LINEALES

En este trabajo encontrarás los siguientes métodos de búsqueda de soluciones de sistemas de ecuaciones lineales y no lineales:


1.   Método de Jacobi
2.   Método Gauss - Seidel
3.   Método de SOR
4.   Método de Newton para sistemas de ecuaciones

En cada método se realiza un breve resumen de los aspectos teóricos, se realiza la implementación y se da un ejemplo de su uso e interpretación.

______________________________________________________________________
Desarrollado por:  
Javier Danilo Castro Faccetti  
Abril 2021.



**Importación de Librerías**

Se importa la librería *NumPy*, para facilitar los cálculos con funciones matemáticas, vectores y matrices.

In [ ]:
import numpy as np

**Método de Jacobi**

Este método busca la convergencia de una sucesión que busca la solución del sistema $Ax=b$ de manera iterativa, mediante la siguiente expresión en forma matricial:

$x^{(k)}=D^{-1}(L+U)+D^{-1}b$

Donde $x^{(k)}$ y $x^{(k-1)}$ representan las aproximaciones a la solución en su k-ésima y anterior a la k-ésima iteración, respectivamente, $D$ una matriz diagonal, $L$ una triangular inferior y $U$ una triangular superior.

Se ha programado el siguiente algoritmo, que recibe como entrada el número de incógnitas del sistema $n$, la matriz $A$, el vector $b$, la aproximación inicial $x^{(0)}$, la tolerancia $tol$ y el número máximo de iteraciones $maxiter$; y devuelve la aproximación a la solución $x$, en un *array*, la tolerancia estipulada $tol$ y el número de iteraciones empleadas $k$.

In [ ]:
def jacobi(n,A,b,x0,tol,maxiter):
  k=0
  x=np.zeros(n)
  while k<maxiter:
    for i in range(0,n,1):
      sum=0
      for j in range(0,n,1):
        if i!=j:
          sum=sum+A[i,j]*x0[j]
      x[i]=(b[i]-sum)/A[i,i]
    k=k+1
    if np.linalg.norm(x-x0)/np.linalg.norm(x)<tol:
      break
    for i in range (0,n,1):
      x0[i]=x[i]
  return x,tol,k

**Método de Gauss-Seidel**

Este método busca la convergencia de una sucesión que busca la solución del sistema $Ax=b$ de manera iterativa, mediante la siguiente expresión en forma matricial:

$x^{(k)}=(D-L)^{-1}Ux^{(k-1)}+(D-L)^{-1}b$

Donde $x^{(k)}$ y $x^{(k-1)}$ representan las aproximaciones a la solución en su k-ésima y anterior a la k-ésima iteración, respectivamente, $D$ una matriz diagonal, $L$ una triangular inferior y $U$ una triangular superior.

Se ha programado el siguiente algoritmo, que recibe como entrada el número de incógnitas del sistema $n$, la matriz $A$, el vector $b$, la aproximación inicial $x^{(0)}$, la tolerancia $tol$ y el número máximo de iteraciones $maxiter$; y devuelve la aproximación a la solución $x$, en un *array*, la tolerancia estipulada $tol$ y el número de iteraciones empleadas $k$.

In [ ]:
def gauss_seidel(n,A,b,x0,tol,maxiter):
  k=0
  x=np.zeros(n)
  while k<maxiter:
    for i in range(0,n,1):
      sum1=0
      sum2=0
      for j in range(0,i,1):
        sum1=sum1+A[i,j]*x[j]
      for j in range(i+1,n,1):
        sum2=sum2+A[i,j]*x0[j]
      x[i]=(b[i]-sum1-sum2)/A[i,i]
    k=k+1
    if np.linalg.norm(x-x0)/np.linalg.norm(x)<tol:
      break
    for i in range (0,n,1):
      x0[i]=x[i]
  return x,tol,k

**Método SOR**

Este método busca la convergencia de una sucesión que busca la solución del sistema $Ax=b$ de manera iterativa, mediante la siguiente expresión en forma matricial:

$x^{(k)}=(D-wL)^{-1}[(1-w)D+wU]x^{(k-1)}+w(D-wL)^{-1}b$

Donde $x^{(k)}$ y $x^{(k-1)}$ representan las aproximaciones a la solución en su k-ésima y anterior a la k-ésima iteración, respectivamente, $D$ una matriz diagonal, $L$ una triangular inferior, $U$ una triangular superior y $w$ un parámetro de relajación.

Este método busca acelerar la convergencia de dicha sucesión utilizando dicho parámetro de relajación $w$ y la anterior expresión matricial del sistema, tratando de minimizar el radio espectral de la matriz de iteración.

Se ha programado el siguiente algoritmo, que recibe como entrada el número de incógnitas del sistema $n$, la matriz $A$, el vector $b$, la aproximación inicial $x^{(0)}$, la tolerancia $tol$ y el número máximo de iteraciones $maxiter$; y devuelve la aproximación a la solución $x$, en un *array*, la tolerancia estipulada $tol$ y el número de iteraciones empleadas $k$.

In [ ]:
def sor(n,A,b,x0,w,tol,maxiter):
  k=0
  x=np.zeros(n)
  while k<maxiter:
    for i in range(0,n,1):
      sum1=0
      sum2=0
      for j in range(0,i,1):
        sum1=sum1+A[i,j]*x[j]
      for j in range(i+1,n,1):
        sum2=sum2+A[i,j]*x0[j]
      x[i]=(1-w)*x0[i]+(1/A[i,i])*(w*(b[i]-sum1-sum2))
    k=k+1
    if np.linalg.norm(x-x0)/np.linalg.norm(x)<tol:
      break
    for i in range (0,n,1):
      x0[i]=x[i]
  return x,tol,k

**Ejemplo de Sistemas de Ecuaciones Lineales**

Se tiene el siguiente sistema de ecuaciones:

$Ax=\begin{bmatrix}
4 & 3 & 0\\
3 & 4 & -1\\
0 & -1 & 4\\ 
\end{bmatrix}\begin{bmatrix}x_{1}\\ x_{2}\\ x_{3}\end{bmatrix}$, $b=\begin{bmatrix}24\\ 30\\ -24\\\end{bmatrix}$

Utilizaremos los algoritmos de los métodos de Jacobi y Gauss-Seidel para obtener aproximaciones con una tolerancia de $1e-03$, con aproximación inicial $x^{(0)}=\begin{bmatrix}1\\ 1\\ 1\end{bmatrix}$.


In [ ]:
jacobi(3,np.matrix('4 3 0; 3 4 -1; 0 -1 4'),np.array([24, 30, -24]),np.ones(3),10**-3,100)

(array([2.998, 3.998, -4.999]), 0.001, 32)

In [ ]:
gauss_seidel(3,np.matrix('4 3 0; 3 4 -1; 0 -1 4'),np.array([24, 30, -24]),np.ones(3),10**-3,100)

(array([3.008, 3.993, -5.002]), 0.001, 8)

Vemos que la mejora propuesta en la sucesión de Gauss-Seidel provee una convergencia más rápida en el método (resuelve el ejemplo en 8 iteraciones, mientras que el de Jacobi emplea 32). Ahora, para obtener un parámetro $w$ para el método de SOR, empleamos la siguiente fórmula:

$w=\frac{2}{1-\sqrt{1+[\rho(T_{j})]^{2}}}$

Donde $T_{j}$ es $(D)^{-1}(L+U)$, es decir, la matriz de iteración del método de Jacobi.

In [ ]:
#Cálculo de Tj

A=np.matrix('4 3 0; 3 4 -1; 0 -1 4')
D=np.diag(np.diag(A))
L=D-np.tril(A)
U=D-np.triu(A)
Tj=np.matmul(np.linalg.inv(D),(L+U))
eigenv=np.linalg.eigvals(Tj)

#Radio espectral

rho=np.amax(np.absolute(eigenv))

#Cálculo de w

w=2/(1+(1-rho**2)**0.5)
w

1.2404082057734578

Con $w$ calculado, utilizamos el método de SOR.

In [ ]:
sor(3,np.matrix('4 3 0; 3 4 -1; 0 -1 4'),np.array([24, 30, -24]),np.ones(3),w,10**-3,100)

(array([3.000, 4.000, -5.000]), 0.001, 7)

El método SOR nos da la aproximación más rápida que los otros dos métodos, al trabajar con la factorización matricial y el parámetro de relajación más óptimo.

**Método de Newton Para Sistemas No Lineales**

Este método es el caso n-dimensional del método de Newton para la búsqueda de raíces en el plano, y se vale de una aproximación inicial lo suficientemente precisa para converger cuadráticamente. Es la expresión algorítmica del siguiente sistema matricial:

$x^{(k)}=x^{(k-1)}-J(x^{(k-1)})^{-1}F(x^{(k-1)})$

Donde $x^{(k)}$ y $x^{(k-1)}$ son las aproximaciones $k$ y $k-1$ a la solución del sistema $F(x)=0$ y $J$ es la matriz jacobiana de dicho sistema.

Se han programado las siguientes funciones que representan dicho método: una principal, denominado *newton*, que toma como valores de entrada el número de incógnitas $n$, la aproximación inicial a la solución $x$, la tolerancia deseada $tol$ y un número máximo de iteraciones $maxiter$, y tiene como salida la aproximación a la solución del sistema $x$, la tolerancia $tol$ y el número de iteraciones realizadas $k$. Esta función (*newton*) utiliza dos funciones auxiliares: *newton_system* y *jacobian*, que toman como argumento la aproximación inicial a la solución $x$ y devuelven un *array* y una matriz con la evaluación del sistema $F$ en dicha aproximación, respectivamente.

In [ ]:
def newton(n,x,tol,maxiter):
  k=0
  while k<maxiter:
    F=newton_system(x)
    J=jacobian(x)
    y=np.linalg.solve(J,-F)
    x=x+y
    k=k+1
    if np.linalg.norm(y)<tol:
      break
  return x,tol,k

**Ejemplo del Método de Newton para Sistemas de Ecuaciones No Lineales**

Se tiene el siguiente sistema no lineal:

$F=
\begin{bmatrix} 
3x_{1}-cos(x_{2}x_{3})-\frac{1}{2}\\
x_{1}^{2}-81(x_{2}+0.1)^{2}+sin(x_{3})+1.06\\
e^{-x_{1}x_{2}}+20x_{3}+\frac{10\pi-3}{3}
\end{bmatrix}$

Se halla su matriz jacobiana, mediante derivación parcial, la cual es:

$J=\begin{bmatrix} 
3 & x_{3}sin(x_{2}x_{3}) & x_{2}sin(x_{2}x_{3})\\
2x_{1} & -162(x_{2}+0.1) & cos(x_{3})\\
-x_{2}e^{-x_{1}x_{2}} & -x_{1}e^{-x_{1}x_{2}} & 20
\end{bmatrix}$

Se ingresan estos valores en las funciones programadas *newton_system* y *jacobian* y luego se ejecuta la función *newton*, con $n=3$, $x=[0.1, 0.1, -0.1]^{T}$, $tol=1e-05$ y $maxiter=100$.

In [ ]:
def newton_system(x):
  return np.array([(3*x[0])-np.cos(x[1]*x[2])-0.5,((x[0])**2)-81*((x[1]+0.1)**2)+np.sin(x[2])+1.06,np.exp(-x[0]*x[1])+20*x[2]+((10*np.pi-3)/3)])

In [ ]:
def jacobian(x):
  return np.array([[3,x[2]*np.sin(x[1]*x[2]),x[1]*np.sin(x[1]*x[2])], [2*x[0],-162*(x[1]+0.1),np.cos(x[2])], [-x[1]*np.exp(-x[0]*x[1]),-x[0]*np.exp(-x[0]*x[1]),20]])

In [ ]:
newton(3,np.array([0.1,0.1,-0.1]),10**-5,100)

(array([ 5.00000000e-01,  3.35521889e-18, -5.23598776e-01]), 1e-05, 5)

La convergencia a la solución real fue bastante rápida, lo que explica la naturaleza cuadrática en casos donde la aproximación inicial es precisa.

# Bibliografía: